-- AlterTable
ALTER TABLE `eventneed` ADD COLUMN `locked` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `offersDeadline` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `eventoffer` MODIFY `status` ENUM('DRAFT', 'SENT', 'REVISED', 'ACCEPTED', 'ACCEPTED_BY_CLIENT', 'DECLINED', 'REJECTED', 'REJECTED_BY_CLIENT', 'WITHDRAWN', 'CANCELLED', 'LOCKED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `offer` MODIFY `status` ENUM('DRAFT', 'SENT', 'REVISED', 'ACCEPTED', 'ACCEPTED_BY_CLIENT', 'DECLINED', 'REJECTED', 'REJECTED_BY_CLIENT', 'WITHDRAWN', 'CANCELLED', 'LOCKED') NOT NULL DEFAULT 'DRAFT';
